/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnimationDemoRouteImport } from './routes/animation-demo'
import { Route as IndexRouteImport } from './routes/index'

const AnimationDemoRoute = AnimationDemoRouteImport.update({
  id: '/animation-demo',
  path: '/animation-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animation-demo': typeof AnimationDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animation-demo': typeof AnimationDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animation-demo': typeof AnimationDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animation-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animation-demo'
  id: '__root__' | '/' | '/animation-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimationDemoRoute: typeof AnimationDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/animation-demo': {
      id: '/animation-demo'
      path: '/animation-demo'
      fullPath: '/animation-demo'
      preLoaderRoute: typeof AnimationDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimationDemoRoute: AnimationDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
