/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoDesignSystemRouteImport } from './routes/demo-design-system'
import { Route as IndexRouteImport } from './routes/index'

const DemoDesignSystemRoute = DemoDesignSystemRouteImport.update({
  id: '/demo-design-system',
  path: '/demo-design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-design-system': typeof DemoDesignSystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-design-system': typeof DemoDesignSystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-design-system': typeof DemoDesignSystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo-design-system'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo-design-system'
  id: '__root__' | '/' | '/demo-design-system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoDesignSystemRoute: typeof DemoDesignSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo-design-system': {
      id: '/demo-design-system'
      path: '/demo-design-system'
      fullPath: '/demo-design-system'
      preLoaderRoute: typeof DemoDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoDesignSystemRoute: DemoDesignSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
